### ISSUE TITLE
CI For Pull Requests 

### ISSUE THREAD

**Issue by rwjblue** [Vestorly/torii#154]
I see from the badge in the `README.md` that y'all are using CircleCI for continuous integration testing.  Could this be enabled to run against pull requests?  It would be very helpful to know if a pull request has broken the tests without having to pull it down and test manually.

Also, the badge links to `https://circleci.com/gh/Vestorly/torii` which gives a 404, I am unsure what CircleCI configuration is needed to enable public read access to the repo.

**Comment by mixonic** [comment]
@jondayton @joebartels Could you take a look here? CircleCI runs, but I don't think it has the right settings enabled to be a publicly view-able CI setup. If you can toggle those or move things over to TravisCI it would be really helpful.

Fwiw, I believe we stuck with CircleCI b/c the run Chrome instead of PhantomJS, and our popup tests fail with PhantomJS.

**Comment by okolehao** [comment]
You should be able to simply go to circleci.com, login with your github credentials and follow your branch.   CircleCI is free.  http://blog.circleci.com/a-step-into-open-source/

**Comment by rwjblue** [comment]
> You should be able to simply go to circleci.com, login with your github credentials and follow your branch. CircleCI is free. http://blog.circleci.com/a-step-into-open-source/

Thanks for the link, but I generally understand how CircleCI works.  This issue is not about my personal fork or setup, but about the setup of this repo (it is not running tests against pull requests and the job history against the master branch is not visible).

> login with your github credentials and follow your branch

This is a feature for the maintainers of this library, not the pull request submitter. As such it doesn't really seem reasonable to require that each contributor personally authorize CircleCI to run the tests in their pull request.

**Comment by rwjblue** [comment]
> we are looking into it, to make sure the right settings are set.

Awesome, thank you!

**Comment by okolehao** [comment]
@rwjblue  we found the setting and turned it on, let us know if that works for you!

**Comment by mixonic** [comment]
@okolehao I'm still not seeing builds reported on pull requests: https://github.com/Vestorly/torii/pull/160 though there is a badge on the readme. Getting the CI on pull requests is really what we need.

**Comment by sukima** [comment]
travis-ci is free of projects like this. And they have rock solid github pull request support out of the box. If CircleCI is just not cutting the mustard it might be worth exploring an alternative.

**Comment by startling** [comment]
Hey, CircleCI engineer here.

Hoping I can help with some context. We have a "Build Fork PRs" setting, that's disabled by default. The reason we've had it disabled is because it shares env vars configured through the UI with forks. This is a security issue for some projects, but other projects (namely: private repositories where collaborators build in forks) *want* env vars shared. We're still working on the best solution to take care of all users, but this should cover most cases.

I've been in contact with @okolehao. They don't have any private env vars configured, so it's totally safe for them to enable this feature, which they're planning on doing.

Thanks for the interest, and sorry for the initial confusion!

**Comment by sukima** [comment]
Huh, I never ran into fork CI before. I've always pulled and pushed a forked branch to the main repo to trigger CI. Interesting, and good to know if someone ever asks about CircleCI; thanks. I guess you have to manage the [tyranny of the default](http://blog.pagefair.com/2015/the-tyranny-of-the-default/) since CI on forks is not a common use case in OSS projects.

**Comment by startling** [comment]
Yeah, a lot of development teams use different combinations of branches / PRs / forks.We try to make our defaults work for everyone, but often it's not clear what the best way is.

**Comment by joebartels** [comment]
@mixonic @rwjblue, The feature, **Project fork pull requests** is now turned on. I tested it against a PR on my forked torii and it :+1:. Closing for now. If anyone see tests not working, definitely give a shout to me or @okolehao.

**Comment by rwjblue** [comment]
@joebartels - Awesome, thank you so much for working on this!

**Comment by mixonic** [comment]
:-D :rocket:
