### ISSUE TITLE
Breaks with Ember Data 1.0.0-beta.19.2

### ISSUE THREAD

**Issue by akshayrawat** [Vestorly/torii#190]
**ember-data#1.0.0-beta.19.1**: `DEPRECATION: You tried to look up 'store:main', but this has been deprecated in favor of 'store:application'.`

**ember-data#1.0.0-beta.19.2**: `Uncaught Error: Attempting to inject an unknown injection: 'store:main'` raised from https://github.com/Vestorly/torii/blob/master/lib/torii/initializers/initialize-torii.js#L14 

---
torii: 0.3.5
ember: 2.0.0-beta.1

**Comment by amk221** [comment]
`service:store`

**Comment by bmac** [comment]
Sorry guys, this one is going to be a little painful for supporting.

Starting with Ember Data-beta.19 I moved the registration of `store:main` into an instance initializer. This was because I didn't quite grasp the concept of the split between initializers and instanceInitializers. Ember Data had some legacy code that supported registering custom stores as `store:main`, `store:application` or `service:store` so Ember Data needed to do a `container.lookup` to figure out which one the user had registered. The deprecation warnings introduced in Ember's 1.12 lead me to believe because of the `container.lookup` deprecations I would have to move this logic into an instanceInitializer.

I believe you are seeing the above errors with beta-19.2 because this line https://github.com/Vestorly/torii/blob/master/lib/torii/initializers/initialize-torii.js#L14 is being run before the "ember-data" `instanceInitializer` is run and is error out because "store:main" isn't registered yet.

Between the beta-19.2 release and Ember Data 1.13 release I finally understood the lesson that @mixonic tired to explain to me when I was initially tackling the container.lookup deprecations. and I realized we could move the registering of "store:main" back to a normal initializer by deprecating all of the different names Ember Data supported for a custom store.

As a result, of moving the registering back to a normal initializer I suspect `torii` should work with Ember Data 1.13. 

However, Ember Data will log a deprecation warning because "store:main" has been deprecated in favor of "service:store".


I hope this explanation saves someone some debugging time.

**Comment by cibernox** [comment]
I've made a PR that moves the eager initialization of the providers to an instance initializer, but still relies in the existence of the deprecated 'store:main'. 
So, this PR allows torii to work with the intersection of `Ember >= 1.12+` and `Ember-data <= beta19.2`. I haven't tried in 1.13 yet.

It might be a good enough intermediate step and another PR can start using `service:store` instance of `store:main` and will work with Ember-data >= 1.13.

**Comment by 2468ben** [comment]
@bmac @cibernox Thank you both for ironing the problem out; I still haven't grasped the initializers & instanceInitializers either, but this explanation/solution helps a lot.
