### ISSUE TITLE
Redirect instead of popup?

### ISSUE THREAD

**Issue by jagthedrummer** [Vestorly/torii#203]
I'm wondering how feasible it would be to have a mode where torii does full page redirects instead of relying on a popup window.

It looks like `lib/torii/services/popup.js` is responsible for opening the popup window, and that `lib/torii/redirect-handler.js` is responsible for recognizing that the provider has redirected back, extracting the token and making it available to the main window before closing the popup.

I'm thinking that a new class like `lib/torii/services/redirect.js` could handle doing a redirect instead of a popup, and then maybe a sub-class of `redirect-handler.js` to do everything except closing the window.

Does that sound possible/reasonable? I'm happy to work on this, just wanted to get a sanity check before I started on anything.

**Comment by mixonic** [comment]
@jagthedrummer the difficulty would be that Torii is based on promises. If we reload the page we obviously cannot restore all the other app state you might have (for example the target URL the user was heading to before unauthenticated redirect), and thus must start relying on hooks and a much more strict and difficult to debug style of development.

I'd be willing to discuss it sometime, and see if we can find a path forward, but I don't believe there is a trivial path to achieve that flow.

However we can support iframes in the page quite easily, and even an iframe that overlays the normal app. A popup-free experience is definitely possible (even easy I think), but not a redirect one. We want to keep the Ember app running.

I'm going to close this but of course you should fire back with any questions or thoughts!

**Comment by jagthedrummer** [comment]
Yeah, I realized that the open promise for the popup could be tricky. I think an iframe solution would be perfect for what I need to do. Would creating `lib/torii/services/iframe.js` based on `lib/torii/services/popup.js` be the place to start?

**Comment by mixonic** [comment]
@jagthedrummer yes! Please give it a whirl. If you are consuming OAuth2 I suggest creating a custom provider that inherits from oauth2-code or whatever Torii provider is correct, then writing a custom `open` on that provider to replace the default one (for example https://github.com/Vestorly/torii/blob/master/lib/torii/providers/oauth2-code.js#L118). Because the popup [encapsulates the request in a promise](https://github.com/Vestorly/torii/blob/master/lib/torii/providers/oauth2-code.js#L125), there is basically very little to change for us to make popup v. iframe an option. We just need a service that can (like popup) open the URL, read the response params, and provide authData objects.

In fact, now that the redirect handler uses localStorage and not window names to communicate, I bet you can even re-use the existing redirect handler. Might be extremely trivial.

Ping me if you run into any blockers.

**Comment by jagthedrummer** [comment]
Will do. Thanks for the pointers!
