### ISSUE TITLE
How to resolve popup with twitter-oauth1

### ISSUE THREAD

**Issue by sheldonnbbaker** [Vestorly/torii#242]
I'm trying to implement the twitter-oauth1 flow, but am confused as to how to resolve with the returned Twitter profile data.

I have `web.widgets.com` (my ember app), `api.widgets.com` (my API), and `auth.widgets.com`: a simple node.js app that handles the oauth dance with twitter (via passportjs) and is opened in the popup by Torii.

My thought was to, after the user authorizes, return the relevant Twitter profile ID to my ember app, and ultimately log the user in to my API by that ID. However, I'm confused by the `code` parameter that the default twitter provider seems to expect - what is that referring to?

The other main problem I've had is in trying to trigger the `storage.torii` event that seems to be responsible for resolving the popup promise. E.g., I try `window.opener.localStorage.setItem('code', twitterProfileId)` but of course run into cross-domain issues.

Can you expand a bit more on the last two steps of the Twitter-specific instructions in the README?

Thanks!

**Comment by mixonic** [comment]
Oof, many questions. I'll do my best.

> My thought was to, after the user authorizes, return the relevant Twitter profile ID to my ember app, and ultimately log the user in to my API by that ID. However, I'm confused by the code parameter that the default twitter provider seems to expect - what is that referring to?

I suggest using a custom token with your own server that represents the user's authenticated state with Twitter.

> Can you expand a bit more on the last two steps of the Twitter-specific instructions in the README?

You should not set the localStorage item on your own.

The steps on [Supporting OAuth 1.0a](https://github.com/Vestorly/torii#supporting-oauth-10a) are as follows:

> 1. Torii provider opens a popup to the app server asking for Twitter auth
> 2. Server redirects to Twitter with the credentials for login
> 3. User enters their credentials at Twitter
> 4. Twitter redirects to app server which completes the authentication
> 5. Server loads the Ember application with a message in the URL, or otherwise transmits a message back to the parent window.
> 6. Ember application in the initial window closes the popup and resolves its provider promise.

Step four is where passport finishes its work. The server should finished the token exchange with Twitter, and instead of rendering the application should return a 302 redirect to the Ember application with a `?code=` param in the URL (step 5). From there, Torii will take care of everything, completing the promise in the parent window and closing the popup (step 6).

Closing this, but let me know if you have any further questions.

**Comment by sheldonnbbaker** [comment]
Perfect - that makes more sense now. Thanks!
