### ISSUE TITLE
this.store undefined in torii-adapter

### ISSUE THREAD

**Issue by mwpastore** [Vestorly/torii#278]
`this.store` (Ember Data) in my `torii-adapters/application.js` is undefined after upgrading Torii from 0.7.0-beta1 to 0.7.0-beta.4. Reverting to beta1 restores the earlier behavior. Do I now need to explicitly inject the Ember Data's store service into my application adapter(s)? Thanks in advance. 

Ember 2.2.2
Ember Data 2.3.2

**Comment by bantic** [comment]
@mwpastore Yes, that's correct. This will be a breaking change in the 0.7.0 release. Since ember-data can be injected using `store: Ember.inject.service()`, some of the complicated code in torii that attempted to [detect the presence of ember-data and auto-inject the store has been removed](https://github.com/Vestorly/torii/pull/271).

Sorry that that bit you, thanks for opening the issue. I'll close it now, please reopen if you have any additional problems.

**Comment by mwpastore** [comment]
That's life on the bleeding edge. :-) Thanks Cory!

**Comment by mwpastore** [comment]
This probably goes without saying for most folks, but for other dummies like me reading this issue, don't forget to change your `this.store` to `this.get('store')` as well.
