### ISSUE TITLE
Transition to after successful login

### ISSUE THREAD

**Issue by kgish** [Vestorly/torii#282]
If a user hits the website using an url other than the `index` and must login, then a useful option would be to redirect the user to the original url once the login is succesful.

I guess the best way to implement this would be to provide an extra configuration boolean value that when set to true would result in the behavior above.

**Comment by bantic** [comment]
@kgish Thanks for this suggestion. This is definitely a useful pattern.
The way we've implemented this before is to catch the unauthenticated transition and store it as an "attempted transition" before redirecting the user to log in. After logging in, check if the session has an "attempted transition" and go there rather than the default.

The authenticatedRoute mixin [uses such a property internally](https://github.com/Vestorly/torii/blob/de370328db922ddeab5bd916c26bfde2aae58f4b/addon/routing/authenticated-route-mixin.js#L23), so if you are opting in to Torii's session management and use `authenticatedRoute` in your router mapping, you should see this behavior by default.

If you wanted to do it without using Torii's authenticatedRoute mixin you could probably do something like this (not you would need to opt in to Torii's session management to do this):

```javascript
// routes/secret.js
export default Ember.Route.extend({
  beforeModel(transition) {
    let session = this.get('session'); // torii's session
    return session.fetch()   // asynchronously check for authenticated state
      .catch(() => {
        // not logged in, store attempted transition and redirect
        session.attemptedTransition = transition;
        return this.transitionTo('login');
      });
  },
  ...
});

// routes/login.js
export default Ember.Route.extend({
  actions: {
    login(email, password) {
      let session = this.get('session');
      session.open({email, password}).then(() => {
        if (session.attemptedTransition) {
          // go to where the user tried to go before redirecting to login
          session.attemptedTransition.retry();
        } else {
          this.transitionTo('some-default-logged-in-page');
        }
      }).catch(() => {
        // incorrect email/pass
      });
    }
  }
});
```

I'll close this, but please let me know if I missed something or that doesn't address your need. I would also be happy to take a PR updating the docs with some information about this pattern because I think others would benefit from it as well.
