### ISSUE TITLE
session not being persisted

### ISSUE THREAD

**Issue by luizkowalski** [Vestorly/torii#306]
I have a torii adapter that after github give me the code, I sent it to my API, and create a new user:

```
import Ember from 'ember';

export default Ember.Object.extend({
  open: function(authentication){
    var code = authentication.authorizationCode;
    return new Ember.RSVP.Promise(function(resolve, reject){
      Ember.$.ajax('http://127.0.0.1:8080/auth/github/code', {
        type: 'POST',
        crossDomain: true,
        dataType: 'json',
        data: { 'code': code },
        success: Ember.run.bind(null, resolve),
        error: Ember.run.bind(null, reject)
      });
    }).then(function(user){
      console.log(user.body);
      return {
        currentUser: user.body
      };
    });
  }
});
```

This is working as expected, and I can see the user on the console after the signup.
but 2 things are not working as expected:
1) sessions is not persisted. If I reload the page with cmd-r, I'm redirected to login route
2) there is nothing in the session. I tried  `console.log(this.get('session.data.currentUser'))` and it is empty

I'm not using ember-simple-auth, just pure torii

**Comment by w-hat** [comment]
At this point, you should not expect your session to be persisted.  In order to persist the session, you must:
 1. Save the user data in `localStorage` or cookies in the `open` hook.
 2. Read the user data out of `localStorage` or cookies in the `fetch` hook.
 3. Remember to actually call the `fetch` hook when you want to load a session.  One way to call the `fetch` hook is to use `authenticatedRoute` in the router.

If you're using localStorage, these hooks are a reasonable place to set header data.  Note that some developers discourage storing any sensitive data in localStorage due to security concerns.  The documentation would do well to provide a more complete example of a torii-adapter.

In response to your second question, try printing `this.get('session.currentUser')` without "data" in the middle.
