### ISSUE TITLE
Google oauth2 providers are outdated

### ISSUE THREAD

**Issue by jfschaff** [Vestorly/torii#331]
Hi, I'm new to Torii, and may be mistaken, but it looks like the Google providers are outdated:
1. they connect to https://accounts.google.com/o/oauth2/auth instead of the new [https://accounts.google.com/o/oauth2/**v2**/auth](https://accounts.google.com/o/oauth2/v2/auth)
2. it looks like Torii does not verify the token (maybe it was not possible with OAuth2 on the previous URL) which makes the authentication vulnerable to the "confused deputy issue" (just repeating what is written [there](https://developers.google.com/identity/protocols/OAuth2UserAgent#tokeninfo-validation)).

**Comment by bantic** [comment]
@jfschaff Thanks for raising. Yeah, those google providers should be updated. I believe the ability to verify the token is new since they were originally written, but either way they should be updated to do that verification. A PR for this would be welcome, and either way I'll leave this open so that it gets addressed. thanks!

**Comment by jfschaff** [comment]
I fixed that in PR #333 which is stuck, but I don't know why...

**Comment by bantic** [comment]
fixed in https://github.com/Vestorly/torii/pull/372 (via #333)
