### ISSUE TITLE
Subclass oauth2-bearer raises en error

### ISSUE THREAD

**Issue by belgoros** [Vestorly/torii#400]
Can I subclass `oauth2-bearer` provider or use it directly in any way ? I tried to do it as follows but failed:

```
import Oauth2BearerProvider from 'torii/providers/oauth2-bearer';
import Ember from 'ember';

export default Oauth2BearerProvider.extend({
  fetch() {
    return new Ember.RSVP.Promise(function(resolve, reject) {
      if(!!localStorage.getItem('token')) {
        return resolve({token: localStorage.getItem('token')});
      } else {
        return reject();
      }
    });
  }
});
```
The above is the content of `my_custom.provider.js` that I put in app/torii-providers folder.

The error I get is:
```
Could not sign you in: Definition of property name by a subclass is required.
```

Thank you.

**Comment by mixonic** [comment]
@belgoros You'll need to use devtools to figure out what is happening is more detail. There isn't much I can offer based on that message.

The file name should likely be `app/providers/my-custom.js`, instead of `my_custom.provider.js`.

Closing this for now, but feel free to re-open it if there is an issue you think can be recreated outside your application!
